### ISSUE TITLE
[ Home Page ] Update the percent bar

### ISSUE THREAD

**Issue by NesaByte** [NesaByte/Maslow-FullFilled#14]
Instead of the current Circular percentage bar, 
![image](https://user-images.githubusercontent.com/53501261/101207565-ca9b9c00-363e-11eb-8629-e606ede498b5.png)

Create this [linear percentage bar](https://pub.dev/packages/percent_indicator):
![image](https://user-images.githubusercontent.com/53501261/101207525-bd7ead00-363e-11eb-980a-5fea626fb4ac.png)

**Comment by rjayroso** [comment]
Hey, I would like to try my hand at updating this to a linear progress bar. Can you please assign me?
