### ISSUE TITLE
Replace AppBar to CurvedNavigationBar

### ISSUE THREAD

**Issue by NesaByte** [NesaByte/Maslow-FullFilled#4]
We have a old looking app, give it a modern look by replacing the AppBar to CurvedNavigationBar.

Check this one:
https://pub.dev/packages/curved_navigation_bar

**Comment by Siddhant-K-code** [comment]
we have to change it in `lib/main.dart`  ??

**Comment by NesaByte** [comment]
hi there! yes, what do you have in mind?

**Comment by Siddhant-K-code** [comment]
![image](https://user-images.githubusercontent.com/55068936/98320188-6d450880-2008-11eb-847f-51a30751d01c.png)

by changing this file's section

**Comment by NesaByte** [comment]
yes, instead of AppBar we change it to CurvedNavigationBar?

**Comment by Siddhant-K-code** [comment]
and use this 
![image](https://user-images.githubusercontent.com/55068936/98320277-9cf41080-2008-11eb-9e91-097a97147ff4.png)

we will modify it ?

**Comment by NesaByte** [comment]
yes please, i'll assign you

**Comment by Siddhant-K-code** [comment]
we have to add background color and we have to add to this ?: 

```
backgroundColor: Colors.blueAccent,
    items: <Widget>[
      Icon(Icons.add, size: 30),
      Icon(Icons.list, size: 30),
      Icon(Icons.compare_arrows, size: 30),
    ],
  ),
  body: Container(color: Colors.blueAccent),
```

**Comment by NesaByte** [comment]
Dont worry about the background color, don't assign anything to it. 
We have a ThemeData that organizes all the colors:
![image](https://user-images.githubusercontent.com/53501261/98322376-41e4fe00-1fb5-11eb-9039-c15cb1e15ecb.png)

**Comment by Siddhant-K-code** [comment]
![image](https://user-images.githubusercontent.com/55068936/98323171-39211600-200f-11eb-9965-d6ab4cd22787.png)

how to fix this error and how to add text in `CurvedNavigationBar`

**Comment by NesaByte** [comment]
remove all these lines:
![image](https://user-images.githubusercontent.com/53501261/98323461-d2bcd900-1fb7-11eb-96e8-0bef7fa158b3.png)

those are for the AppBar.

**Comment by Siddhant-K-code** [comment]
then, for Text ?

**Comment by NesaByte** [comment]
no more text

**Comment by Siddhant-K-code** [comment]
how will be print the title and all ?

**Comment by Siddhant-K-code** [comment]
![image](https://user-images.githubusercontent.com/55068936/98323606-2d821f00-2010-11eb-88b8-5d4c55d62ff7.png)
is it fine ?

**Comment by NesaByte** [comment]
no need to print the title, its included in the appbar. we remove it completely.

**Comment by NesaByte** [comment]
change the Icon.* to home and calender

**Comment by Siddhant-K-code** [comment]
![image](https://user-images.githubusercontent.com/55068936/98323787-b13c0b80-2010-11eb-88d3-1105eeab890b.png)

Done, Pls check it once

**Comment by NesaByte** [comment]
superb, looks good to me. do u have an emulator? what does it looks like now?

**Comment by Siddhant-K-code** [comment]
Thanks, but, sorry my laptop is unable to handle emulator.

**Comment by NesaByte** [comment]
oooh i see, need to check it out how it looks like. but overall good job

**Comment by NesaByte** [comment]
👍  thank you, I'll test it out soon tomorrow. It's late-night here right now.

**Comment by NesaByte** [comment]
fixed this at -> [commit - ed74cb](https://github.com/NesaByte/Moslow_MyNeeds/commit/ed74cb617da91190d1669ec4018be7e81b5603c2)
