### ISSUE TITLE
[ Question Page ] Update the QuestionBank

### ISSUE THREAD

**Issue by NesaByte** [NesaByte/Maslow-FullFilled#7]
Write a simple checklist about Moslow's Hierarchy of Needs:

example:
 * physiological needs 
 - [ ] air
 - [ ]  water
 - [ ]  food
 - [ ]  shelter
 - [ ]  sleep
 - [ ]  clothing
 - [ ]  reproduction

 ( and so on  from the photo below. . . )

![needs](https://2ij7hk3p1vra3uhoox411gzf-wpengine.netdna-ssl.com/wp-content/uploads/2020/04/maslow-1024x724.jpg)

extra [link](https://www.simplypsychology.org/maslow.html) for help.

**Comment by NesaByte** [comment]
Added a simple QuestionBank here -> [commit 5053ff56](https://github.com/NesaByte/Moslow_MyNeeds/commit/5053ff567d973d47c0200f4aa0e0e5ac500c59a1)

![image](https://user-images.githubusercontent.com/53501261/98911836-41f06c80-2493-11eb-9c5e-ed7704355605.png)

**Comment by NesaByte** [comment]
turn the QuestionBank's Questions into an Interrogative sentence to ask users.

**Comment by rubyAnneB** [comment]
am working on this- please assign
